/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_MUSICLIBSERVERSTUB_H_
#define JSONRPC_CPP_STUB_MUSICLIBSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class musiclibserverstub : public jsonrpc::AbstractServer<musiclibserverstub>
{
    public:
        musiclibserverstub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<musiclibserverstub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("test", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_STRING, "param1",jsonrpc::JSON_STRING, NULL), &musiclibserverstub::testI);
            this->bindAndAddMethod(jsonrpc::Procedure("addAlbum", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_OBJECT, NULL), &musiclibserverstub::addAlbumI);
            this->bindAndAddMethod(jsonrpc::Procedure("removeAlbum", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &musiclibserverstub::removeAlbumI);
            this->bindAndAddMethod(jsonrpc::Procedure("initLibraryFromJsonFile", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING, NULL), &musiclibserverstub::initLibraryFromJsonFileI);
            this->bindAndAddMethod(jsonrpc::Procedure("toJsonFile", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_BOOLEAN, "param1",jsonrpc::JSON_STRING,"param2",jsonrpc::JSON_STRING, NULL), &musiclibserverstub::toJsonFileI);
        }

        inline virtual void testI(const Json::Value &request, Json::Value &response)
        {
            response = this->test(request[0u].asString());
        }
        inline virtual void addAlbumI(const Json::Value &request, Json::Value &response)
        {
            response = this->addAlbum(request[0u]);
        }
        inline virtual void removeAlbumI(const Json::Value &request, Json::Value &response)
        {
            response = this->removeAlbum(request[0u].asString());
        }
        inline virtual void initLibraryFromJsonFileI(const Json::Value &request, Json::Value &response)
        {
            response = this->initLibraryFromJsonFile(request[0u].asString());
        }
        inline virtual void toJsonFileI(const Json::Value &request, Json::Value &response)
        {
            response = this->toJsonFile(request[0u].asString(), request[1u].asString());
        }
        virtual std::string test(const std::string& param1) = 0;
        virtual bool addAlbum(const Json::Value& param1) = 0;
        virtual bool removeAlbum(const std::string& param1) = 0;
        virtual bool initLibraryFromJsonFile(const std::string& param1) = 0;
        virtual bool toJsonFile(const std::string& param1, const std::string& param2) = 0;
};

#endif //JSONRPC_CPP_STUB_MUSICLIBSERVERSTUB_H_
